---
title: "About"
author: "Raymond Hu"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Repo URL: https://github.com/ryzhu75/final-proj-v1
Instacart Data Source: https://www.instacart.com/datasets/grocery-shopping-2017
In-store Data Source: https://www.dunnhumby.com/careers/engineering/sourcefiles


Instacart is a grocery pick-up service operating in the U.S. and Canada. Users can submit an order and Instacart will pick up and deliver from one of their partnered grocery stores. In 2017, Instacart released data surrounding 3 million orders from more than 200,000 users. Released data variables including, product ID, order number, user id, the order's time of day, department, aisle, reorders, time since last order just to name a few. While the data is comprehensive, they are separated into six disparate files. Most of the variable names are consistent however I will continue to transform and clean the data as I answer different questions. By analyzing this data, I can investigate questions including: what items are most frequently reordered? At what times do people order certain items? Can we segment users based on order size, frequency, and type? What items tend to be ordered together? All of these are asked specifically in regards to online grocery shopping.

The second data set I have downloaded is on household level transactions from 2,500 frequent shopper households for over a period of two years (obtained from dunnhumby.com). It includes data on products purchased, time of day, coupon usage, and demographic data and more. This data is on in-store shopping, not online delivery shopping like Instacart. Like the previous dataset, the data is separated into multiple files which will need to be combined appropraitely depending on the question I am trying to answer.  Using this data and the Instacart dataset together, I can answer questions like, how do shopping habits differ between in-store shopping and online shopping? How do habits change based on time of day and week between the two methods?




