---
title: "final_proj"
author: "Raymond Hu"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(dplyr)
library(janitor)
library(gganimate)
library(tidymodels)
library(gt)
library(webshot)
```

```{r Load in instacart data, include = FALSE, cache = TRUE}
instacart_products <- read.csv("raw/instacart_2017_05_01/products.csv")
instacart_orders <- read.csv("raw/instacart_2017_05_01/orders.csv")
instacart_order_products_train <- read.csv("raw/instacart_2017_05_01/order_products__train.csv")
instacart_order_products_prior <- read.csv("raw/instacart_2017_05_01/order_products__prior.csv")
instacart_departments <- read.csv("raw/instacart_2017_05_01/departments.csv")
instacart_aisles <- read.csv("raw/instacart_2017_05_01/aisles.csv")
```

```{r Create master data tibble, include = FALSE}
# Combine train and prior data sets
instacart_order_products_combine <- instacart_order_products_prior %>% 
  rbind(instacart_order_products_train) %>% 
  arrange(order_id)

# Combine product info with order data to create a master file
instacart_master <- 
  instacart_order_products_combine %>% 
  full_join(instacart_products, by = "product_id") %>% 
  left_join(instacart_orders, by = "order_id") %>% 
  left_join(instacart_departments, by = "department_id") %>% 
  left_join(instacart_aisles, by = "aisle_id")

```

```{r load in dunnhumby data, include = FALSE, cache = TRUE}

# Read in all dunnhumby data and clean

dunn_transaction_data <- read.csv("raw/dunnhumby - The Complete Journey CSV/transaction_data.csv") %>% 
  clean_names()
dunn_product <- read.csv("raw/dunnhumby - The Complete Journey CSV/product.csv") %>% 
  clean_names()
dunn_hh_demographic <- read.csv("raw/dunnhumby - The Complete Journey CSV/hh_demographic.csv") %>% 
  clean_names()
dunn_coupon_redempt <- read.csv("raw/dunnhumby - The Complete Journey CSV/coupon_redempt.csv") %>% 
  clean_names()
dunn_coupon <- read.csv("raw/dunnhumby - The Complete Journey CSV/coupon.csv") %>% 
  clean_names()
dunn_causal_data <- read.csv("raw/dunnhumby - The Complete Journey CSV/causal_data.csv") %>% 
  clean_names()
dunn_campaign_table <- read.csv("raw/dunnhumby - The Complete Journey CSV/campaign_table.csv") %>% 
  clean_names()
dunn_campaign_desc <- read.csv("raw/dunnhumby - The Complete Journey CSV/campaign_desc.csv") %>% 
  clean_names()
```


```{r Compare dunn and instacart data, echo = FALSE}
# Join Dunnhumby product information to transaction data

dunn_transaction_data_product <- dunn_transaction_data %>% 
  left_join(dunn_product, by = "product_id")

# Combine both density plots to compare the density of purchases through the day
# between in store and instacart data

ggplot() +
  geom_density(aes(x = trans_time/100), 
              fill = "red", 
              data = dunn_transaction_data, 
              adjust = 3, 
              alpha =  0.5) +
  geom_density(aes(x = order_hour_of_day), 
              fill = "blue", 
              data = instacart_orders, 
              adjust = 3, 
              alpha = 0.5) +
  labs(title = "Distribution of Grocery Store Purchases throughout the Day",
      y = "% of Total Purchases",
      x = "Hour of Day") +
  scale_y_continuous(labels = scales::percent) +
  theme_classic() +
  annotate("text", 
           x = 7.25, 
           y= .08, 
           label = "Instacart", 
           color = "blue", 
           size = 4.5) +
  annotate("text", 
           x = 13.75, 
           y= .095, 
           label = "Brick & Mortar \n Grocer", 
           color = "red", 
           size = 4.5) 

```

```{r Explore Instacart Data, echo = FALSE, cache = TRUE}

# View orders by department_id

instacart_master %>% 
  ggplot(aes(x = department_id)) +
  geom_histogram(binwidth = 1)

# View orders by department_id throughout time of day
instacart_master %>% 
  ggplot(aes(x = department_id)) +
  geom_density() +
  transition_manual(order_hour_of_day) +
  labs(title = "Hour of Day: {frame}")

```

```{r Transform Instacart_Master File to import to shiny web app, echo = FALSE, cache = TRUE}

# Plot the graph of # product orders (organized by department) throughout the time of day, with a reveal animation over time of day
# Faceted by day of week

insta_productnum_day_week  <- instacart_master %>% 
  mutate(department = as.character(department)) %>% 
  group_by(order_dow, order_hour_of_day, department, department_id) %>% 
  count() %>% 
  filter(!is.na(order_hour_of_day))

insta_productnum_day_week %>% 
  ggplot(aes(x = order_hour_of_day, y = n, color = department)) +
  geom_line() +
  facet_wrap(~order_dow) +
  theme_classic()

saveRDS(insta_productnum_day_week, file = "ecommerce_final/instacart_dow_product.rds")

```

```{r Work with Dunnhumby Data, echo = FALSE}

## Dunn data
# Wrangle dunn transaction data 

dunn_trans_hour <- dunn_transaction_data_product %>% 
  mutate(trans_hour = trans_time - (trans_time %% 100)) %>% 
  group_by(basket_id, trans_hour) %>%
  count() %>% 
  group_by(trans_hour) %>% 
  count()

# Calculate total transactions (for unit purposes later)

dunn_total_transactions <- sum(dunn_trans_hour$n)

# Edit table once again to get percentages and change unit of hour of day
dunn_trans_hour <- dunn_trans_hour %>% 
  ungroup(trans_hour) %>% 
  mutate(trans_hour = trans_hour/100,
         percent = n/dunn_total_transactions)
  
# Sample plot data

dunn_trans_hour_plot <- dunn_trans_hour %>%   
  ggplot(aes(x = trans_hour, y = percent)) +
  geom_line() +
  transition_reveal(trans_hour)


## Instacart

# Initial clean of data

instacart_trans_hour <- instacart_master %>% 
  group_by(order_id, order_hour_of_day) %>% 
  count() %>% 
  group_by(order_hour_of_day) %>% 
  count() %>% 
  filter(!is.na(order_hour_of_day))

# Calculate total # of transactions

instacart_total_transactions <- sum(instacart_trans_hour$n)

# Edit table once again to get percentages

instacart_trans_hour <- instacart_trans_hour %>% 
  ungroup(order_hour_of_day) %>% 
  mutate(percent = n/instacart_total_transactions,
         trans_hour = order_hour_of_day) %>% 
  select(trans_hour, n, percent)

# Sample Plot data

instacart_trans_hour_plot <- instacart_trans_hour %>% 
  ggplot(aes(x = order_hour_of_day, y = n/instacart_total_transactions*100)) +
  geom_line()
    

## Combine data and export RDS for shiny web app

combine_trans_hour <- 
  bind_rows(list(dunn_trans_hour = dunn_trans_hour, 
                 instacart_trans_hour = instacart_trans_hour),
            .id = 'source')

saveRDS(combine_trans_hour, file = "ecommerce_final/combine_trans_hour.rds")

# Plot
combine_trans_hour %>% 
  ggplot(aes(x = trans_hour, y = percent, color = source)) +
  geom_line() +
  theme_classic() +
  labs(title = "Distribution of Grocery Store Transactions throughout the Day",
      y = "% of Total Purchases",
      x = "Hour of Day") +
  scale_y_continuous(labels = scales::percent) +
  scale_color_discrete(name = "", labels = c("Brick and Mortar", "Instacart")) +
  theme(legend.position = "bottom") +
  transition_reveal(trans_hour)
    
```

```{r Basket Sizes, echo = FALSE}

# Wrangle dunn data to get average unique item basket_size for every hour 

dunn_master <- dunn_transaction_data_product 

dunn_basket_size <- dunn_master %>% 
  mutate(trans_hour = (trans_time - (trans_time %% 100))/100) %>% 
  group_by(basket_id, trans_hour) %>% 
  count() %>% 
  group_by(trans_hour) %>% 
  summarize(basket_size = mean(n)) 


# Clean instacart data to get average unique item basket_size for every hour \

instacart_basket_size <- instacart_master %>% 
  group_by(order_id, order_hour_of_day) %>% 
  count() %>% 
  group_by(order_hour_of_day) %>% 
  summarize(basket_size = mean(n)) %>% 
  mutate(trans_hour = order_hour_of_day) %>% 
  select(-order_hour_of_day)

# Combine the two datasets

combine_basket_size <- 
  
  # This allows me to identify the original source
  
  bind_rows(list(dunn_basket_size = dunn_basket_size, 
                 instacart_basket_size = instacart_basket_size),
            .id = 'source') 

# Save this data table into a rds file to be used in the shiny web app

saveRDS(combine_basket_size, file = "ecommerce_final/combine_basket_size.rds")

# Sample plot that I will place into the shiny web app

combine_plot <- combine_basket_size %>% 
  ggplot(aes(x = trans_hour, y = basket_size, color = source)) +
  geom_line() +
  labs(title = "Average Number of Unique Items per Basket") +
  scale_color_discrete(name = "", labels = c("Brick and Mortar", "Instacart")) +
  scale_x_continuous(name = "Hour of Day") +
  scale_y_continuous(name = "# Unique Items / Basket", limits = c(0, 12)) +
  theme_classic() +
  theme(legend.position = "bottom")
```

```{r Reordering Model, echo = FALSE, cache = TRUE}

prior_size <- instacart_master %>% 
  group_by(days_since_prior_order, order_id) %>% 
  count() %>% 
  mutate(items = n) %>% 
  select(-n) %>% 
  ungroup(days_since_prior_order, order_id)

saveRDS(prior_size, file = "ecommerce_final/prior_size.rds")


# Open png to which a plot can be saved to 

png(file = "ecommerce_final/prior_size_image.png",
    width = 750,
    height = 375)

# Plot a graph between days since previous order and # unique items in basket

prior_size %>% 
  ggplot(aes(x = items, y = days_since_prior_order)) +
  geom_jitter() +
  geom_smooth(method = "lm") +
  scale_y_continuous(name = "Days Since Previous Order") +
  scale_x_continuous(name = "Unique Items in Basket") +
  labs(title = "Relationship Between Order Size and Order Frequency") +
  theme_classic() 

# Close the png file to which the previous plot has been saved
      
dev.off()


# Create a simpel regression of items on days since last order

model <- lm(days_since_prior_order ~ items, data = prior_size) 

# Display results in a formatted gt table

gt_model <- model %>% 
  tidy(conf.int = TRUE) %>% 
  select(term, estimate, std.error, conf.low, conf.high) %>% 
  gt() %>% 
  cols_label(term = "Term",
              estimate = "Estimate",
             std.error = "Standard Error",
             conf.low = "95% CI (Low)",
             conf.high = "95% CI (High)") %>% 
  fmt_number(decimals = 4,
             columns = 2:5)

# Save the table as an image file to export to shiny

gtsave(gt_model, "prior_size_table.png", path = "ecommerce_final/prior_size_table.png")

```

```{r Instacart Purchases by Department, echo = FALSE}

# Create a bar graph breaking down total purchase distribution by department

# Summarizes data to count purchases by department

insta_by_department <- instacart_master %>% 
  group_by(department) %>% 
  count() %>% 
  arrange(desc(n)) 
  
# Create a variable that totals all purchases (for calculating percentages later)

total_purchases <- sum(insta_by_department$n)

# Create a new percentage variable that divides department purchases by total purchases

insta_by_department <- insta_by_department %>% 
  mutate(percent = n/total_purchases)

# Save as RDS for shinyapp

saveRDS(insta_by_department, file = "ecommerce_final/insta_by_department.rds")

# Plot the desired bar graph of department by percentage of purchases 

insta_by_department %>% 
  ggplot(aes(x = reorder(department, -percent), y = 100*percent)) +
  geom_col() +
  scale_y_continuous(name = "% of Total Purchases") +
  scale_x_discrete(name = "Department") +
  labs(title = "Purchase Distribution by Department") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust = .9, hjust = .95))
  
```










